runtime: python39

handlers:
- url: /assets
  static_dir: assets

- url: /main.js
  static_files: main.js
  upload: main.js

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /
  static_files: index.html
  upload: index.html